// <auto-generated />
using System;
using ContractMonthlyClaimSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractMonthlyClaimSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117134724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Auth.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Auth.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Auth.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ContractClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcademicManagerDecision")
                        .HasColumnType("int");

                    b.Property<int?>("AcademicManagerUserId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LecturerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LecturerUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramCoordinatorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramCoordinatorDecision")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramCoordinatorUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicManagerUserId");

                    b.HasIndex("LecturerUserId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ProgramCoordinatorUserId");

                    b.ToTable("ContractClaims");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ContractClaimDocument", b =>
                {
                    b.Property<int>("ContractClaimId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedFileId")
                        .HasColumnType("int");

                    b.HasKey("ContractClaimId", "UploadedFileId");

                    b.HasIndex("UploadedFileId");

                    b.ToTable("ContractClaimsDocuments");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.LecturerModule", b =>
                {
                    b.Property<int>("LecturerUserId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("LecturerUserId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("LecturerModules");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.UploadedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Auth.AppUserRole", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.Auth.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.Auth.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ContractClaim", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.Auth.AppUser", "AcademicManagerUser")
                        .WithMany()
                        .HasForeignKey("AcademicManagerUserId");

                    b.HasOne("ContractMonthlyClaimSystem.Models.Auth.AppUser", "LecturerUser")
                        .WithMany()
                        .HasForeignKey("LecturerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.Auth.AppUser", "ProgramCoordinatorUser")
                        .WithMany()
                        .HasForeignKey("ProgramCoordinatorUserId");

                    b.Navigation("AcademicManagerUser");

                    b.Navigation("LecturerUser");

                    b.Navigation("Module");

                    b.Navigation("ProgramCoordinatorUser");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.ContractClaimDocument", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.ContractClaim", "ContractClaim")
                        .WithMany()
                        .HasForeignKey("ContractClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractClaim");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.LecturerModule", b =>
                {
                    b.HasOne("ContractMonthlyClaimSystem.Models.Auth.AppUser", "LecturerUser")
                        .WithMany()
                        .HasForeignKey("LecturerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContractMonthlyClaimSystem.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LecturerUser");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Auth.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ContractMonthlyClaimSystem.Models.Auth.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
